# Generated by Django 2.0.1 on 2018-01-04 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='produto',
            name='cor',
        ),
        migrations.AddField(
            model_name='produto',
            name='cor',
            field=models.ManyToManyField(to='produtos.Cor'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.RemoveField(
            model_name='produto',
            name='tamanho',
        ),
        migrations.AddField(
            model_name='produto',
            name='tamanho',
            field=models.ManyToManyField(to='produtos.Tamanho'),
        ),
    ]
