# Generated by Django 2.0.1 on 2018-01-05 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_auto_20180104_2032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cor',
            options={'verbose_name': 'cor', 'verbose_name_plural': 'cores'},
        ),
        migrations.RemoveField(
            model_name='produto',
            name='referencia',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='slug',
        ),
    ]
