# Generated by Django 2.0.1 on 2018-01-05 00:56

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_auto_20180104_2144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='cor',
            options={'ordering': ['nome'], 'verbose_name': 'cor', 'verbose_name_plural': 'cores'},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['tipo', 'nome']},
        ),
        migrations.AlterModelOptions(
            name='tamanho',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='tipo',
            options={'ordering': ['nome']},
        ),
        migrations.RemoveField(
            model_name='cor',
            name='tipo',
        ),
        migrations.AddField(
            model_name='cor',
            name='tipo',
            field=models.ManyToManyField(to='produtos.Tipo'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True, max_length=builtins.max, null=True, verbose_name='Descrição'),
        ),
        migrations.RemoveField(
            model_name='tamanho',
            name='tipo',
        ),
        migrations.AddField(
            model_name='tamanho',
            name='tipo',
            field=models.ManyToManyField(to='produtos.Tipo'),
        ),
        migrations.RemoveField(
            model_name='tipo',
            name='categoria',
        ),
        migrations.AddField(
            model_name='tipo',
            name='categoria',
            field=models.ManyToManyField(to='produtos.Categoria'),
        ),
    ]
