# Generated by Django 2.0.1 on 2018-01-05 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_auto_20180104_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Descrição'),
        ),
    ]
