# Generated by Django 2.0.1 on 2018-01-05 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_auto_20180104_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='slug',
            field=models.SlugField(default='slug-name', max_length=150),
        ),
        migrations.AlterField(
            model_name='produto',
            name='foto',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=''),
        ),
    ]
