# Generated by Django 2.0.1 on 2018-01-05 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_auto_20180104_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
