# Generated by Django 2.0.1 on 2018-01-05 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_auto_20180104_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='referencia',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
