# Generated by Django 2.0.1 on 2018-01-05 02:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0010_produto_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True, default=django.utils.timezone.now, verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='foto',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, upload_to='madamechique/static/img'),
            preserve_default=False,
        ),
    ]
