# Generated by Django 2.0.1 on 2018-01-06 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0011_auto_20180104_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoProduto',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.ImageField(blank=True, upload_to='img')),
            ],
        ),
        migrations.RemoveField(
            model_name='produto',
            name='foto',
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='disponivel',
            field=models.BooleanField(default=True, verbose_name='Disponível'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.FloatField(verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='referencia',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Referência'),
        ),
        migrations.AddField(
            model_name='fotoproduto',
            name='cod_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.Produto'),
        ),
    ]
