# Generated by Django 2.0.1 on 2018-01-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0012_auto_20180106_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo',
            name='categoria',
            field=models.ManyToManyField(db_table='produtos_tipo_categoria', to='produtos.Categoria'),
        ),
    ]
