# Generated by Django 2.0.1 on 2018-02-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0014_auto_20180214_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.FloatField(verbose_name='Preço'),
        ),
    ]
