# Generated by Django 2.0.1 on 2018-02-12 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('logradouro', models.CharField(max_length=255, verbose_name='Nome')),
                ('numero', models.CharField(max_length=10, verbose_name='Nome')),
                ('complemento', models.CharField(max_length=255, verbose_name='Nome')),
                ('pontoref', models.CharField(max_length=255, verbose_name='Nome')),
                ('bairro', models.CharField(max_length=70, verbose_name='Nome')),
                ('cidade', models.CharField(max_length=70, verbose_name='Nome')),
                ('estado', models.CharField(max_length=2, verbose_name='Nome')),
                ('cep', models.CharField(max_length=10, verbose_name='Nome')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
