# Generated by Django 2.0.1 on 2018-02-13 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserComplements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('celular', models.CharField(max_length=11, verbose_name='Celular')),
                ('data_nasc', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Sexo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='bairro',
            field=models.CharField(max_length=70, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='cep',
            field=models.CharField(max_length=10, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='cidade',
            field=models.CharField(max_length=70, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='complemento',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='estado',
            field=models.CharField(max_length=2, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='logradouro',
            field=models.CharField(max_length=255, verbose_name='Logradouro'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='numero',
            field=models.CharField(max_length=10, verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='pontoref',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ponto de referência'),
        ),
    ]
